### ISSUE TITLE
Please add Open With Favorite External Tool 1 Ctrl+Alt+1

### ISSUE THREAD

**Issue by paulvi** [basti1302/startexplorer#45] opened 2014-01-28 02:34 UTC
Please add `Open With Favorite External Tool 1` <kbd>Ctrl+Alt+1</kbd>,
`Open With Favorite External Tool 2` <kbd>Ctrl+Alt+2</kbd>.

While integrating with any console #37 may require a considerable work and will not be as universal and StartExplorer is now, please consider using standard Eclipse External Tool feature. Because the may be quite a lot of them configured, there is idea use only those that are added as Favorites.

So the challenge is whether it is easy to pass selected path to External Tool via Launch Configuration without created new one.

![external-tool-launch](https://f.cloud.github.com/assets/1614482/2015827/e74ebf56-87c4-11e3-871f-a4fc0a11c091.png)

**Comment by basti1302** [comment] 2015-07-24 13:04
Sounds like a duplicate of #11

**Closed** 2015-07-24 13:04 UTC
